---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: ".eslintrc.yaml"
  fixme:
    enabled: true
    checks:
      XXX:
        enabled: false
      TODO:
        enabled: false

checks:
  return-statements:
    enabled: false
  method-complexity:
    config:
      threshold: 10

ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
