---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: 'eslint-9'
    config:
      config: 'eslint.config.mjs'
  fixme:
    enabled: true
    checks:
      XXX:
        enabled: false
      TODO:
        enabled: false

checks:
  return-statements:
    enabled: false
  method-complexity:
    config:
      threshold: 10

ratings:
  paths:
    - '**.js'
exclude_paths:
  - test/
