#!/bin/bash
# Update Haraka TLD files

CURL=$(which curl 2>/dev/null)

if [ $? -ne 0 ]; then
    echo "Error: curl not found"
    exit 1
fi

$CURL -f -s -S -o etc/public-suffix-list https://publicsuffix.org/list/effective_tld_names.dat

$CURL -f -s -S -o etc/top-level-tlds https://data.iana.org/TLD/tlds-alpha-by-domain.txt
$CURL -f -s -S -o etc/two-level-tlds http://george.surbl.org/two-level-tlds
$CURL -f -s -S -o etc/three-level-tlds http://george.surbl.org/three-level-tlds
$CURL -f -s -S -o etc/extra-tlds http://rss.uribl.com/hosters/hosters.txt
