name: Lint

on: [ push ]

env:
  CI: true
  node-version: 16

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-node@v3
      name: Node ${{ env.node-version }}
      with:
        node-version: ${{ env.node-version }}

    - uses: actions/checkout@v3

    - run: npm install

    - run: npm run lint
